# Generated by Django 4.1.2 on 2022-11-04 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='comment2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments1', to='home.comments'),
        ),
    ]
