# Generated by Django 4.1.2 on 2022-12-13 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_reply_comment2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reply',
            name='number2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
